version: '3.8'

networks:
  aw-network:
    driver: bridge

services:
  web:
    image: desafio-back-cb
    container_name: 'web'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    networks:
      - aw-network
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml