CREATE TABLE BRANCH(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    cnpj VARCHAR(18) NOT NULL,
    city VARCHAR(50) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    type VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL,
    registration_date TIMESTAMP NOT NULL,
    last_update TIMESTAMP
);